<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Cnss.Cotisation.Domain\Cnss.Cotisation.Domain.csproj" />
    <ProjectReference Include="..\Cnss.Cotisation.Application\Cnss.Cotisation.Application.csproj" />
    <ProjectReference Include="..\..\Shared\Cnss.Shared.Domain\Cnss.Shared.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\Cnss.Shared.Application\Cnss.Shared.Application.csproj" />
    <ProjectReference Include="..\..\Shared\Cnss.Shared.Infrastructure\Cnss.Shared.Infrastructure.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
