// <auto-generated />
using System;
using Cnss.Affiliation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cnss.Affiliation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AffiliationDbContext))]
    [Migration("20260407144726_RefactorToDomainEntities")]
    partial class RefactorToDomainEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("affiliation")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cnss.Affiliation.Domain.Aggregats.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aff_employee_identifier");

                    b.Property<string>("EmployerIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aff_employee_employer_identifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aff_employee_first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aff_employee_last_name");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aff_employee_registration_number");

                    b.HasKey("Id");

                    b.HasIndex("EmployerIdentifier");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("aff_employees", "affiliation");

                    b.HasData(
                        new
                        {
                            Id = "SAL-0001",
                            EmployerIdentifier = "EMP-0001",
                            FirstName = "John",
                            LastName = "Doe",
                            RegistrationNumber = "MAT-001"
                        },
                        new
                        {
                            Id = "SAL-0002",
                            EmployerIdentifier = "EMP-0001",
                            FirstName = "Jane",
                            LastName = "Doe",
                            RegistrationNumber = "MAT-002"
                        });
                });

            modelBuilder.Entity("Cnss.Affiliation.Domain.Aggregats.Employer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aff_employer_identifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aff_employer_company_name");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aff_employer_registration_number");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("aff_employers", "affiliation");

                    b.HasData(
                        new
                        {
                            Id = "EMP-0001",
                            CompanyName = "ACME SARL",
                            RegistrationNumber = "RCCM-001"
                        });
                });

            modelBuilder.Entity("Cnss.Affiliation.Infrastructure.Persistence.AffiliationOutboxMessageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("aff_outbox_message_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("aff_outbox_attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("aff_outbox_event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("aff_outbox_last_error");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aff_outbox_locked_until_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aff_outbox_occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("aff_outbox_payload");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aff_outbox_processed_on_utc");

                    b.Property<DateTime?>("ProcessingStartedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aff_outbox_processing_started_on_utc");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aff_outbox_routing_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aff_outbox_status");

                    b.HasKey("Id");

                    b.HasIndex("LockedUntilUtc");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("aff_outbox_messages", "affiliation");
                });
#pragma warning restore 612, 618
        }
    }
}
