// <auto-generated />
using Cnss.Affiliation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cnss.Affiliation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AffiliationDbContext))]
    partial class AffiliationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("affiliation")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cnss.Affiliation.Infrastructure.Persistence.AffiliationEmployeeRecord", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aff_employee_identifier");

                    b.Property<string>("EmployerIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aff_employee_employer_identifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aff_employee_first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aff_employee_last_name");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aff_employee_registration_number");

                    b.HasKey("Identifier");

                    b.HasIndex("EmployerIdentifier");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("aff_employees", "affiliation");

                    b.HasData(
                        new
                        {
                            Identifier = "SAL-0001",
                            EmployerIdentifier = "EMP-0001",
                            FirstName = "John",
                            LastName = "Doe",
                            RegistrationNumber = "MAT-001"
                        },
                        new
                        {
                            Identifier = "SAL-0002",
                            EmployerIdentifier = "EMP-0001",
                            FirstName = "Jane",
                            LastName = "Doe",
                            RegistrationNumber = "MAT-002"
                        });
                });

            modelBuilder.Entity("Cnss.Affiliation.Infrastructure.Persistence.AffiliationEmployerRecord", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aff_employer_identifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aff_employer_company_name");

                    b.PrimitiveCollection<string[]>("EmployeeIdentifiers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("aff_employer_employee_identifiers");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aff_employer_registration_number");

                    b.HasKey("Identifier");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("aff_employers", "affiliation");

                    b.HasData(
                        new
                        {
                            Identifier = "EMP-0001",
                            CompanyName = "ACME SARL",
                            EmployeeIdentifiers = new[] { "SAL-0001", "SAL-0002" },
                            RegistrationNumber = "RCCM-001"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
