// <auto-generated />
using System;
using Cnss.Cotisation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cnss.Cotisation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CotisationDbContext))]
    [Migration("20260407144726_RefactorToDomainEntities")]
    partial class RefactorToDomainEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cotisation")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cnss.Cotisation.Domain.Aggregats.Declaration", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_identifier");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("cot_declaration_is_published");

                    b.HasKey("Id");

                    b.ToTable("cot_declarations", "cotisation");

                    b.HasData(
                        new
                        {
                            Id = "DEC-0001",
                            IsPublished = true
                        });
                });

            modelBuilder.Entity("Cnss.Cotisation.Domain.Entities.DeclarationItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_item_identifier");

                    b.Property<string>("DeclarationIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_item_declaration_identifier");

                    b.Property<string>("EmployeeIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_item_employee_identifier");

                    b.Property<decimal>("GrossSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cot_declaration_item_gross_salary");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationIdentifier");

                    b.ToTable("cot_declaration_items", "cotisation");

                    b.HasData(
                        new
                        {
                            Id = "DIT-0001",
                            DeclarationIdentifier = "DEC-0001",
                            EmployeeIdentifier = "SAL-0001",
                            GrossSalary = 1500m
                        },
                        new
                        {
                            Id = "DIT-0002",
                            DeclarationIdentifier = "DEC-0001",
                            EmployeeIdentifier = "SAL-0002",
                            GrossSalary = 2000m
                        });
                });

            modelBuilder.Entity("Cnss.Cotisation.Infrastructure.Persistence.CotisationOutboxMessageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cot_outbox_message_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("cot_outbox_attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cot_outbox_event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("cot_outbox_last_error");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cot_outbox_locked_until_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cot_outbox_occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cot_outbox_payload");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cot_outbox_processed_on_utc");

                    b.Property<DateTime?>("ProcessingStartedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cot_outbox_processing_started_on_utc");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cot_outbox_routing_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_outbox_status");

                    b.HasKey("Id");

                    b.HasIndex("LockedUntilUtc");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("cot_outbox_messages", "cotisation");
                });

            modelBuilder.Entity("Cnss.Cotisation.Domain.Aggregats.Declaration", b =>
                {
                    b.OwnsOne("Cnss.Cotisation.Domain.ValuesObject.DeclarationPeriod", "Period", b1 =>
                        {
                            b1.Property<string>("DeclarationId")
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("cot_declaration_month");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("cot_declaration_year");

                            b1.HasKey("DeclarationId");

                            b1.ToTable("cot_declarations", "cotisation");

                            b1.WithOwner()
                                .HasForeignKey("DeclarationId");

                            b1.HasData(
                                new
                                {
                                    DeclarationId = "DEC-0001",
                                    Month = 3,
                                    Year = 2026
                                });
                        });

                    b.OwnsOne("Cnss.Cotisation.Domain.ValuesObject.EmployerIdentifier", "EmployerIdentifier", b1 =>
                        {
                            b1.Property<string>("DeclarationId")
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("cot_declaration_employer_identifier");

                            b1.HasKey("DeclarationId");

                            b1.ToTable("cot_declarations", "cotisation");

                            b1.WithOwner()
                                .HasForeignKey("DeclarationId");

                            b1.HasData(
                                new
                                {
                                    DeclarationId = "DEC-0001",
                                    Value = "EMP-0001"
                                });
                        });

                    b.Navigation("EmployerIdentifier")
                        .IsRequired();

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Cotisation.Domain.Entities.DeclarationItem", b =>
                {
                    b.HasOne("Cnss.Cotisation.Domain.Aggregats.Declaration", null)
                        .WithMany("Items")
                        .HasForeignKey("DeclarationIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Cotisation.Domain.Aggregats.Declaration", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
