// <auto-generated />
using System;
using Cnss.Cotisation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cnss.Cotisation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CotisationDbContext))]
    [Migration("20260407133415_AddOutbox")]
    partial class AddOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cotisation")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cnss.Cotisation.Infrastructure.Persistence.CotisationDeclarationItemRecord", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_item_identifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cot_declaration_item_amount");

                    b.Property<string>("DeclarationIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_item_declaration_identifier");

                    b.Property<string>("EmployeeIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_item_employee_identifier");

                    b.Property<decimal>("GrossSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cot_declaration_item_gross_salary");

                    b.HasKey("Identifier");

                    b.HasIndex("DeclarationIdentifier");

                    b.ToTable("cot_declaration_items", "cotisation");

                    b.HasData(
                        new
                        {
                            Identifier = "DIT-0001",
                            Amount = 75m,
                            DeclarationIdentifier = "DEC-0001",
                            EmployeeIdentifier = "SAL-0001",
                            GrossSalary = 1500m
                        },
                        new
                        {
                            Identifier = "DIT-0002",
                            Amount = 100m,
                            DeclarationIdentifier = "DEC-0001",
                            EmployeeIdentifier = "SAL-0002",
                            GrossSalary = 2000m
                        });
                });

            modelBuilder.Entity("Cnss.Cotisation.Infrastructure.Persistence.CotisationDeclarationRecord", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_identifier");

                    b.Property<string>("EmployerIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_employer_identifier");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("cot_declaration_is_published");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("cot_declaration_month");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("cot_declaration_year");

                    b.HasKey("Identifier");

                    b.HasIndex("EmployerIdentifier", "Year", "Month");

                    b.ToTable("cot_declarations", "cotisation");

                    b.HasData(
                        new
                        {
                            Identifier = "DEC-0001",
                            EmployerIdentifier = "EMP-0001",
                            IsPublished = true,
                            Month = 3,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Cnss.Cotisation.Infrastructure.Persistence.CotisationOutboxMessageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cot_outbox_message_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("cot_outbox_attempt_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cot_outbox_event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("cot_outbox_last_error");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cot_outbox_locked_until_utc");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cot_outbox_occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cot_outbox_payload");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cot_outbox_processed_on_utc");

                    b.Property<DateTime?>("ProcessingStartedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cot_outbox_processing_started_on_utc");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cot_outbox_routing_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_outbox_status");

                    b.HasKey("Id");

                    b.HasIndex("LockedUntilUtc");

                    b.HasIndex("Status", "OccurredOnUtc");

                    b.ToTable("cot_outbox_messages", "cotisation");
                });

            modelBuilder.Entity("Cnss.Cotisation.Infrastructure.Persistence.CotisationDeclarationItemRecord", b =>
                {
                    b.HasOne("Cnss.Cotisation.Infrastructure.Persistence.CotisationDeclarationRecord", null)
                        .WithMany("Items")
                        .HasForeignKey("DeclarationIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Cotisation.Infrastructure.Persistence.CotisationDeclarationRecord", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
