// <auto-generated />
using Cnss.Cotisation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cnss.Cotisation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CotisationDbContext))]
    partial class CotisationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cotisation")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cnss.Cotisation.Infrastructure.Persistence.CotisationDeclarationItemRecord", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_item_identifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cot_declaration_item_amount");

                    b.Property<string>("DeclarationIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_item_declaration_identifier");

                    b.Property<string>("EmployeeIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_item_employee_identifier");

                    b.Property<decimal>("GrossSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cot_declaration_item_gross_salary");

                    b.HasKey("Identifier");

                    b.HasIndex("DeclarationIdentifier");

                    b.ToTable("cot_declaration_items", "cotisation");

                    b.HasData(
                        new
                        {
                            Identifier = "DIT-0001",
                            Amount = 75m,
                            DeclarationIdentifier = "DEC-0001",
                            EmployeeIdentifier = "SAL-0001",
                            GrossSalary = 1500m
                        },
                        new
                        {
                            Identifier = "DIT-0002",
                            Amount = 100m,
                            DeclarationIdentifier = "DEC-0001",
                            EmployeeIdentifier = "SAL-0002",
                            GrossSalary = 2000m
                        });
                });

            modelBuilder.Entity("Cnss.Cotisation.Infrastructure.Persistence.CotisationDeclarationRecord", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_identifier");

                    b.Property<string>("EmployerIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cot_declaration_employer_identifier");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("cot_declaration_is_published");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("cot_declaration_month");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("cot_declaration_year");

                    b.HasKey("Identifier");

                    b.HasIndex("EmployerIdentifier", "Year", "Month");

                    b.ToTable("cot_declarations", "cotisation");

                    b.HasData(
                        new
                        {
                            Identifier = "DEC-0001",
                            EmployerIdentifier = "EMP-0001",
                            IsPublished = true,
                            Month = 3,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Cnss.Cotisation.Infrastructure.Persistence.CotisationDeclarationItemRecord", b =>
                {
                    b.HasOne("Cnss.Cotisation.Infrastructure.Persistence.CotisationDeclarationRecord", null)
                        .WithMany("Items")
                        .HasForeignKey("DeclarationIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Cotisation.Infrastructure.Persistence.CotisationDeclarationRecord", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
