<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cnss.Cotisation.Infrastructure\Cnss.Cotisation.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Affiliation\Cnss.Affiliation.Infrastructure\Cnss.Affiliation.Infrastructure.csproj" />
  </ItemGroup>

</Project>
